dask/dask-drmaa

- .travis.yml
- Dockerfile-master
- Dockerfile-slave
- README.md
- dask_drmaa/__init__.py
- dask_drmaa/core.py
- dask_drmaa/tests/test_core.py
- docker-compose.yml
- requirements.txt
- run-master.sh
- setup.py
> Draft of simple Python library

- Dockerfile-master
- Dockerfile-slave
- add_worker.sh
- dask_drmaa/__init__.py
- dask_drmaa/adaptive.py
- dask_drmaa/core.py
- dask_drmaa/sge.py
- dask_drmaa/tests/test_adaptive.py
- dask_drmaa/tests/test_core.py
- dask_drmaa/tests/test_sge.py
This adds a very dumb `Adaptive` cluster class (stolen from `distributed.deploy.adaptive`) that looks at tasks running on the scheduler and uses the stated resources to inform SGECluster worker requests.
The current policy is unsophisticated.  If there are unrunnable tasks then it launches a worker with more memory than is required by the first task.  Ideally we would want to scale out in some proportional way, or look at many unrunnable tasks, etc..  
Additionally there is currently no scale down mechanism.  The easiest way to get this to work is to inform the workers of their job id to allow the scheduler to map backwards from worker to SGE task to kill.  A bit of google searching revealed that the environment variable `$JOB_ID` or `$PBS_JOBID` should be set, unfortunately this doesn't …
> WIP - Adaptive Scaling on SGE

- dask_drmaa/__init__.py
- dask_drmaa/adaptive.py
- dask_drmaa/core.py
- dask_drmaa/tests/test_adaptive.py
Previously this failed due to issues with dask/distributed.
Those have since been resolved.  We are now able to close workers
from the scheduler and clean up the drmaa jobs accordingly.
> Enable adaptive to close workers

- dask_drmaa/__init__.py
- dask_drmaa/core.py
This helps to robustly clean up workers if the user does not clean up well.
> Clean up all lingering workers at exit

- .travis.yml
- Dockerfile-master
- Dockerfile-slave
- dask_drmaa/core.py
- dask_drmaa/tests/test_core.py
This allows for a few things:
1.  Users can customize this script to their liking, introducing various
environment variables as they see fit.
2.  We get to use DRMAA/SGE environment variables within this script
See https://github.com/dask/dask-drmaa/issues/14
Problems
-------
I can't seem to find an environment variable for job/task ID that is DRMAA-generic.  Does this exist?  The solution so far uses SGE-specific terms, which we probably shouldn't merge.  cc @davidr
> Use bash script rather than dask-worker executable

- dask_drmaa/adaptive.py
- dask_drmaa/core.py
- dask_drmaa/tests/test_adaptive.py
This is still a work in progress. I still have a few pieces that were previously all in `._adapt` that need to be added back in. This depends on https://github.com/dask/distributed/pull/1311
> Subclass distributed.Adaptive

- README.rst
The extra space after the bullet point was causing the second line in the first bullet point to render as a block quote.
> Fix bullet point formatting in README

- MANIFEST.in
Make sure the LICENSE and README are included. Also ensure any compiled Python code is not included.
> Add a basic manifest to aid in packaging

- MANIFEST.in
This is needed by `setup.py` to determine the requirements of the package. So this definitely needs to land in the `sdist` or any other deployed product.
> Package the requirements.txt file

- setup.py
Makes the `entry_points` section, `console_scripts`, a dictionary instead of embedded in a string. Makes it a little easier to parse using external programs.
> Tweak the `entry_points` format in `setup.py`

- README.rst
- dask_drmaa/core.py
- dask_drmaa/tests/test_core.py
SGE seems to have some issues running scripts that are not in the local directory.  I haven't spent much time investigating why this is, but have pushed up a change to copy the script into the current working directory that I hope both effective and innocuous.
Critical feedback welcome
> Copy user-provided script to local directory

- dask_drmaa/tests/test_core.py
Fixes https://github.com/dask/dask-drmaa/issues/42
The `test_stop_workers_politely` test has been a bit flaky. Given the test is trying to shutdown a worker and compute results at the same time, this seems like part of the problem. To try and fix this, wait until the worker is shutdown completely before trying to retrieve results. Otherwise it seems to have issues.
> Fix flakiness in `test_stop_workers_politely`

- dask_drmaa/tests/test_adaptive.py
Fixes https://github.com/dask/dask-drmaa/issues/41
The test, `test_dont_request_on_many_short_tasks`, has been rather flaky. However it is unclear on how best to fix it because its failure mode may be caused by SGE laggy behavior. So simply marking it as a known failure. If someone comes up with a fix, we can always revisit.
> Mark `test_dont_request_on_many_short_tasks` xfail

- .travis.yml
- Dockerfile-master
- Dockerfile-slave
- ci/scripts/conda_setup.sh
- dask_drmaa/tests/test_adaptive.py
Appears that Miniconda includes `conda` 4.4.10, which is problematic when installing some packages (e.g. `ca-certificates`). This causes the CI to fail. A fix is deployed in `conda` 4.4.11. However has not made its way into Miniconda. This fixes oure CI build to upgrade to the newer `conda` version.
xref: https://github.com/conda/conda/issues/6811
> Update conda to 4.4.11

- dask_drmaa/core.py
Fixes https://github.com/dask/dask-drmaa/issues/32
Closes https://github.com/dask/dask-drmaa/pull/33
Closes https://github.com/dask/dask-drmaa/pull/46
Improves the handling of Job ID for different types of DRMAA clusters. Namely creates a session with DRMAA and queries `drmsInfo` on that session. This provides information about the specific cluster, which we then check against the supported types (i.e. SLURM, LSF, and SGE). Using this check, we set the correct environment variables for the Job ID and Task ID for each scheduler. In addition, we set what we call `JOB_PARAM` for each cluster, which represents the string the scheduler will replace with the Job ID when submitting a job. This should address some issues encountered by SLURM and LSF users.
> Fix handling of Job ID

- dask_drmaa/core.py
- env.yml
- requirements.txt
It looks like `io_loop` is not a a parameter of PeriodicCallback in Tornado 5, which makes master fail (see a build on my [fork](https://travis-ci.org/lesteve/dask-drmaa/builds/351210528). I am guessing Tornado 5 is picked up by pip from `pip install https://github.com/dask/distributed.git`. It is a new problem since Tornado 5 has been released a few days ago (March 5th according to https://pypi.python.org/pypi/tornado).
Not sure what the policy is for Tornado 4 vs Tornado 5. Do you want to support both? I guess the Python 2.7 build could use Tornado 4 and the 3.6 one use Tornado if that is the case.
> Tornado 5 fix

- dask_drmaa/core.py
Appears we missed getting `io_loop` added back to `PeriodicCallback` in PR ( https://github.com/dask/dask-drmaa/pull/61 ) (sorry for missing that). As a result, we can get hangs in some cases when trying to start the `dask-drmaa` cluster. This readds the `io_loop` argument, which should fix that issue.
cc @mrocklin @lesteve
> Readd io_loop to PeriodicCallback

- README.rst
- dask_drmaa/adaptive.py
- dask_drmaa/sge.py
- dask_drmaa/tests/test_adaptive.py
- requirements.txt
- Support passing kwargs to `distributed.Adaptive.__init__`, which now includes arguments like `minimum` and `maximum` [number of workers].
- Add an optional `workers` argument to `_retire_workers()` to match https://github.com/dask/distributed/pull/1797 (currently throws a `TypeError`)
> Compatibility fixes with distributed 1.21.3

- dask_drmaa/core.py
- dask_drmaa/tests/test_core.py
Makes sure that `start_workers` can take `n = 0` and `stop_workers` can take `worker_ids = []`. Namely by not starting or stopping any workers. Previously these errored out in a cryptic way. So by simply avoiding erroring out, this is an improvement.
> Allow starting and stopping no workers

- .gitattributes
Shell scripts are intended to be run in ubuntu-based docker images, so remove carriage returns on windows. (Mentioned in #64)
> Minor, add line ending handling for windows

- dask_drmaa/core.py
This makes `dask-drmaa` work on `PBS/Torque`
I'm not sure what exactly the difference between JOB_PARAM and JOB_ID should be.
Here are all PBS related env variables:
```
PBS_ENVIRONMENT=PBS_INTERACTIVE
PBS_GPUFILE=/var/spool/torque/aux//7641024.hpc-main3.cm.clustergpu
PBS_JOBCOOKIE=D57B25C527004153B093AC7B41FC9CA8
PBS_JOBID=7641024.hpc-main3.cm.cluster
PBS_JOBNAME=STDIN
PBS_MICFILE=/var/spool/torque/aux//7641024.hpc-main3.cm.clustermic
PBS_MOMPORT=15003
PBS_NODEFILE=/var/spool/torque/aux//7641024.hpc-main3.cm.cluster
PBS_NODENUM=0
PBS_NP=1
PBS_NUM_NODES=1
PBS_NUM_PPN=1
PBS_O_HOME=/home/mnoethe
PBS_O_HOST=hpc-gw3.cm.cluster
PBS_O_LANG=en_US.UTF-8
PBS_O_LOGNAME=mnoethe
PBS_O_MAIL=/var/spool/mail/mnoethe
PBS_O_PATH=/home/mnoethe/.conda/envs/dask/bin:/sl6/sw/python/anaconda36/bin:/sl6/sw/cmake …
```
> Add Torque job info

- dask_drmaa/core.py
As discussed in [issue 72](https://github.com/dask/dask-drmaa/issues/72), I fleshed out the docstring for DRMAACluster. Hopefully it is now a little bit easier to use.
> Flesh out doctstring for DRMAACluster

- dask_drmaa/core.py
When trying to determine the type of DRMAA scheduler implementation being used, query for information using the same session object used to launch jobs later.
> Use `get_session` for scheduler type inquiry

- Dockerfile-master
- Dockerfile-slave
Switch to using the stable version of distributed for now. There are some config changes in progress in dask and distributed that don't really affect us, but don't work correctly without using dev versions of both and we have only been using dev versions of distributed. Should help to test against stable versions of both if we need to make another release too.
> Use stable distributed for CI

- dask_drmaa/tests/test_core.py
This test has been flaky historically. However it appears to now be reliably failing on both Python 2 & 3. Would be good to fix it once the cause is understood. Though it is not a critical failure, so we can tolerate marking it as a failure and tracking for now. There are other changes planned (e.g. updating worker startup and shutdown) that may end up fixing it.
xref: https://github.com/dask/dask-drmaa/issues/93
> Mark `test_stop_single_worker` as a known failure
